export { firstMovieOnPage } from "./firstMovieOnPage";
export { arrayFromString } from "./arrayFromString";
export { firstElementsFromArray } from "./firstElementsFromArray";
export { scrollToY } from "./scrollToY";
export { loadMoreCard } from "./loadMoreCard";
export { getMovieTitleFromPath } from "./getMovieTitleFromPath";
export { nextQuestion } from "./nextQuestion";
export { capitalizeFirstLetter } from "./capitalizeFirstLetter";
export { generatorUrl} from "./generatorUrl";
// export { sliceMoviesPerPage } from './sliceMoviesPerPage';
