export { getManyMoviesByTitle } from "./getManyMoviesByTitle";
export { getMovieById } from "./getMovieById";
export { getMovieCast } from "./getMovieCast";
export { getTopRatedMovies } from "./getTopRatedMovies";
export { getTrailer } from "./getTrailer";
export { getUpcomingMovies } from "./getUpcomingMovies";
export { getManyMoviesByIds } from "./getManyMoviesByIds";
export { getPopularMovies } from "./getPopularMovies";
// export { getMovieByTitle } from "./getMovieByTitle";
// export {getRattings} from "./getRattings";
